apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Shahithya07/argo-cd.git
    targetRevision: main
    path: sw-catalogs
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
